[book]
title = "OrientDB"
author = "community"
description = "OrientDB documentation"
src = "./"

[build]
build-dir = "orientdb-book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]

[output.html.fold]
enable = true
level = 0

[output.html.search]
limit-results = 15

[preprocessor.variables.variables]
book.CE_name= "orientdb.devmunity"
book.CE_link = "https://repo1.maven.org/maven2/com/orientechnologies/orientdb.devmunity/3.1.19/orientdb.devmunity-3.1.19.zip"
book.TP2_name = "orientdb.devmunity-tp2"
book.TP2_link = ""
book.TP3_name = "orientdb.devmunity-tp3"
book.TP3_link = "https://repo1.maven.org/maven2/com/orientechnologies/orientdb.devmunity-tp2/3.1.19/orientdb.devmunity-tp2-3.1.19.tar.gz"
book.TP3Spatial_name = "orientdb.devmunity-spatial"
book.TP3Spatial_link = "https://repo1.maven.org/maven2/com/orientechnologies/orientdb-tp3/3.1.19/orientdb-tp3-3.1.19.tar.gz"
book.source_repository = "https://github.com/orientechnologies/orientdb/blob/develop/"
book.lastGA = "3.2.42"
book.currentVersion =  "3.1.19"
book.demoDBVersion_screenshots ="0.76"
book.javase = "https://docs.oracle.com/javase/8/docs"
book.javadoc = "https://orientdb.dev/javadocs/develop"
